### ISSUE TITLE
Issue no tests found

### ISSUE THREAD

**Issue by andrei-serguienko** [game-ci/unity-test-runner#106]
Hello,
I have an issue, I have searched everywhere and I ask in Discord but nobody can find a solution.

Where I run my tests is like no tests were found I have this output :
```
=================
Analyze result:
✅ Test Results - 0/0 - Passed in 0.000s
```
I have a new Unity project with 2 simple tests: SimplePlayModeTest and SimpleEditModeTest

I can run the tests in the Unity Editor everything is working.
I don't know what I have missed or misunderstood.

If you have any idea where it can come from? I will be very happy to know 😸

**Comment by webbertakken** [comment]
If you use the default path, then you shouldn't specify the projectPath parameters

That said it's probably related to the assembly definition not being correctly configured.

- My recommendation is that you copy the example project within test runner action repository and go from there to set up your workflow.
- Once you know your workflow is 100% correct, you can change up the project part, that way you know for your workflow is done.

**Comment by sacOO7** [comment]
No, I don't think it's an assembly definition issue. I am facing the same issue. It works well with `webbertakken/unity-test-runner@v2.0-alpha-1` but doesn't work at all with `gameci/unity-test-runner@v2.0-alpha-1`

**Comment by davidmfinol** [comment]
> `gameci/unity-test-runner@v2.0`.


We don't have 2.0. 
Did you mean `gameci/unity-test-runner@v2` ?

**Comment by davidmfinol** [comment]
In your logs, there is this:
```
Assembly 'Library/ScriptAssemblies/PlayMode.dll' will not be loaded due to errors:
Reference has errors 'IO.Ably'.
Assembly 'Library/ScriptAssemblies/EditMode.dll' will not be loaded due to errors:
Reference has errors 'IO.Ably'.
Assembly 'Assets/Ably/Plugins/IO.Ably.dll' will not be loaded due to errors:
IO.Ably references strong named Newtonsoft.Json Assembly references: 9.0.0.0 Found in project: 10.0.0.0.
```

Your tests aren't running because the assembly definitions aren't being loaded because of a versioning issue with Json.Net.
I've found that getting a version of Json.Net that works well across all Unity versions/platforms can be tricky. I'm currently (and would recommend) using pure UPM to install this fork: https://github.com/jilleJr/Newtonsoft.Json-for-Unity

**Comment by robGG1997** [comment]
@davidmfinol I've made sure to check my test assemblies `.asmdef` and also checked my logs and no reference to unloaded references, the project I work on is open source much like this one so you can take a look at the action https://github.com/ChainSafe/web3.unity/actions/runs/6130712963/job/16640060573, it's a package test runner, am I doing anything wrong?

**Comment by robGG1997** [comment]
> @davidmfinol I've made sure to check my test assemblies `.asmdef` and also checked my logs and no reference to unloaded references, the project I work on is open source much like this one so you can take a look at the action https://github.com/ChainSafe/web3.unity/actions/runs/6130712963/job/16640060573, it's a package test runner, am I doing anything wrong?

The tests directory is https://github.com/ChainSafe/web3.unity/tree/rob/automated-unity-tests-603/src/UnityPackages/io.chainsafe.web3-unity/Tests/Runtime runs and passes locally in the [UnitySampleProject](https://github.com/ChainSafe/web3.unity/tree/rob/automated-unity-tests-603/src/UnitySampleProject)

**Comment by davidmfinol** [comment]
Following up on discord: https://discord.com/channels/710946343828455455/1150042726595821688

**Comment by AdamB-BVG** [comment]
having a similar issue in unity 6 where it's running a single test in the addressables package, but running none of my project's tests. The ci run passes, despite a glaring compiler error in the project.
