### ISSUE TITLE
Uninitialized bash variables lead to spurious errors in the logs

### ISSUE THREAD

**Issue by mikeage** [game-ci/unity-test-runner#108]
In run_tests.sh, there are variables that are tested without ever being set, leading to errors such as (this is from tests running edit mode only):
```
/steps/run_tests.sh: line 162: [: =: unary operator expected
/steps/run_tests.sh: line 180: [: -gt: unary operator expected
```
This occurs because https://github.com/game-ci/unity-test-runner/blob/main/action/steps/run_tests.sh#L124 sets `PLAY_MODE_EXIT_CODE`, but this line is only executed if the condition at https://github.com/game-ci/unity-test-runner/blob/main/action/steps/run_tests.sh#L108 is true. Otherwise, `PLAY_MODE_EXIT_CODE` is never set, and the comparison on line 180 throws this error.

The same is true for `EDIT_MODE_EXIT_CODE` and the tests of `EDIT_MODE` and `PLAY_MODE` themselves. All should be initialized at the beginning of the script.

**Comment by davidmfinol** [comment]
I believe this issue can be closed now because of https://github.com/game-ci/unity-test-runner/pull/146, right?

**Comment by mikeage** [comment]
I'm actually not positive, because in the end I didn't wind up using this, but from looking at the code, yes, I think it should be fixed. I'll close the issue on that assumption.
