### ISSUE TITLE
Checkout Package from sub folder of a Repository

### ISSUE THREAD

**Issue by sivatejachigicherla** [game-ci/unity-test-runner#133]
I'm trying to checkout package from a sub folder of repository and I get this error : 

![error](https://user-images.githubusercontent.com/17229809/124863106-2878d380-dfd4-11eb-98b7-564196a97cfe.png)

**Comment by webbertakken** [comment]
This is not at all related to test-runner.

Please open your issue at https://github.com/actions/checkout if you want to use a different format than prescribed.
