### ISSUE TITLE
Add option to reduce GitHub UI check marks

### ISSUE THREAD

**Issue by davidmfinol** [game-ci/unity-test-runner#169]
**Context**

If a user has a lot of tests, they may be unable to use this action to display the test results through the GitHub UI.
They may run into the error: `Only 65535 characters are allowed`
Furthermore, even if they don't run into this error, they may not want to see a bunch of check marks when they are really only interested in seeing if any tests failed.

**Suggested solution**

Add an option to the `unity-test-runner` called `githubCheckFailed`, which, if enabled, would not show green check marks for each passing test case. 
Instead, it would only show red crosses for each failed test. 
If there are too many failed tests, it would perhaps take only the first few to show.

**Considered alternatives**

We could instead try to find a way to split the requests to the GitHub API into smaller pieces.
There may be a better name rather than `githubCheckFailed`

**Additional details**

This is to fix https://github.com/game-ci/unity-test-runner/issues/142

**Comment by webbertakken** [comment]
Personally I feel we should use great defaults instead of creating another configuration option here.

We could do an automated check for the amount of tests and determine how to best display meaningful checks.

**Comment by MrGadget1024** [comment]
This is surely what I'm running into now - see #214
