### ISSUE TITLE
Add chownToUser

### ISSUE THREAD

**Issue by skjalgsm-statespace** [game-ci/unity-test-runner#186]
**Context**

I am running game.ci using my own ubuntu runners and I am getting a problem on the second run where it wont do the checkout because of permission issues
![image](https://user-images.githubusercontent.com/99833648/175029660-cc1a9ec4-674c-411e-966d-c401b40dd619.png)

**Suggested solution**

I got around a similar problem when using unity-builder and its build artifacts by adding chownFilesTo in that workflow. But this option does not exist in unity-test-runner, so I suggest that its added for the test and code coverage artifacts.

You can find the code that is ran in build.sh in unity-builder (for both mac and ubuntu)
```
# Make a given user owner of all artifacts
if [[ -n "$CHOWN_FILES_TO" ]]; then
  chown -R "$CHOWN_FILES_TO" "$BUILD_PATH_FULL"
  chown -R "$CHOWN_FILES_TO" "$UNITY_PROJECT_PATH"
fi
```

Adapting this for unity-test-runner it would probably be something like (in run_tests.sh)
```
# Make a given user owner of all artifacts
if [[ -n "$CHOWN_FILES_TO" ]]; then
  chown -R "$CHOWN_FILES_TO" "$FULL_ARTIFACTS_PATH"
  chown -R "$CHOWN_FILES_TO" "$FULL_COVERAGE_RESULTS_PATH"
  chown -R "$CHOWN_FILES_TO" "$UNITY_PROJECT_PATH"
fi
```

**Comment by davidmfinol** [comment]
Done by https://github.com/game-ci/unity-test-runner/pull/187 and available with v2.0.3

Thank you @skjalgsm-statespace !
