### ISSUE TITLE
Code Coverage does not write any output anywhere

### ISSUE THREAD

**Issue by dustuu** [game-ci/unity-test-runner#228]
**Bug description**

The code coverage feature does not work and does not write output, but fails silently with no errors. The test results are outputted as expected; only the code coverage results are missing.

**How to reproduce**

Example workflow job: https://github.com/kemocade/Kemocade.Vrc.Data/blob/main/.github/workflows/release.yml#L16C5-L16C5
(The "test" job only)

Example run: https://github.com/kemocade/Kemocade.Vrc.Data/actions/runs/5399441106/jobs/9806562948

- **Expected behavior**

Results of the code coverage operation should be placed into the CodeCoverage folder.

**Additional details**

Unity Version: 2019.4.31f1

**Comment by dustuu** [comment]
It turns out that this problem is because the code I want to test is inside of a package. This is currently not supported, but seems that it will be supported with #164 

Hopefully that can get merged soon.

**Comment by davidmfinol** [comment]
PR  #164 has been merged.
@dustuu I'm closing this on the assumption that this solves this issue, but please re-open if this issue remains.
