### ISSUE TITLE
Unity no longer supports manual activation of Personal licenses

### ISSUE THREAD

**Issue by poi-vrc** [game-ci/unity-test-runner#235]
My builds starting from few hours ago keep failing because of licensing issues. After some investigation and found out this in 
https://license.unity3d.com/manual :

> Unity no longer supports manual activation of Personal licenses. For more information, see: https://docs.unity3d.com/Manual/LicensesAndActivation.html

Does it mean we no longer can use CI for Unity builds without a Professional license anymore? 😱

**Comment by webbertakken** [comment]
There's a thread going on about this on our discord: https://discord.com/channels/710946343828455455/1138586951604248666

**Comment by GabLeRoux** [comment]
Closing as duplicate of https://github.com/game-ci/documentation/issues/408

Feel free to continue discussion in other issue 👍

**Comment by pridroid** [comment]
How do I get access to the discord channel?  and the thread?

**Comment by GabLeRoux** [comment]
> How do I get access to the discord channel? and the thread?

https://game.ci/discord :+1:

**Comment by cgbeaulieu** [comment]
Confirmed the workaround above still works today.
