### ISSUE TITLE
v4.1.0 causing activation to fail when using manual offline activation

### ISSUE THREAD

**Issue by poi-vrc** [game-ci/unity-test-runner#253]
**Bug description**

I was previously using `game-ci/unity-test-runner@v4` on my builds. And activated Unity personal edition in GitHub Actions using the manual activation method for months:
https://github.com/game-ci/documentation/issues/408

**How to reproduce**

Activate using manual activation and paste the ulf content as a secret in `UNITY_LICENSE`.
Use `game-ci/unity-test-runner@v4` in the workflow file, which will resolve to `v4.1.0` and run a build.
The activation will fail.
![image](https://github.com/game-ci/unity-test-runner/assets/77053052/f6153314-2a44-41d6-b811-3e20ea8b9a94)

- **Expected behavior**

Successfully activate, build and test.

**Additional details**

Reverting to v4.0.0 by using `game-ci/unity-test-runner@v4.0.0` can activate successfully.

**Comment by AndrewKahr** [comment]
Did you pass in `UNITY_EMAIL` and `UNITY_PASSWORD` in addition to the license?

**Comment by poi-vrc** [comment]
No, I did not pass those secrets. It was working without the email and password previously.
Are they required since v4.1.0?

**Comment by AndrewKahr** [comment]
Indeed it is now required. It was actually supposed to be required since v4.0.0 but the code didn't align with Unity-Builder properly. I will update the release notes to make that more clear

**Comment by AndrewKahr** [comment]
I should also note it needs to be the same credentials as the account used to activate the license.

Apologies for the inconvenience!

**Comment by poi-vrc** [comment]
Thanks. I will modify my workflows later on.
