### ISSUE TITLE
Fails if XML file other than NUnit format is output to artifactsPath

### ISSUE THREAD

**Issue by nowsprinting** [game-ci/unity-test-runner#285]
**Bug description**

Fails if XML file other than NUnit format is output to artifactsPath.

**How to reproduce**

Test outputs a file with a ".xml" extension other than the NUnit format.

**Expected behavior**

Ignore non-test result XML files.

**Additional details**

https://github.com/game-ci/unity-test-runner/blob/05a00ef5aced57c6f2d3b8f2a98d2239a1f24c0f/src/model/results-check.ts#L21-L28

**Comment by GabLeRoux** [comment]
@coderabbitai, please review the file located at src/model/results-check.ts. There is an issue where files with a “.xml” extension, not in NUnit format, are causing errors when processed. Can you suggest a fix for this?

**Comment by nowsprinting** [comment]
Thanks!!
