### ISSUE TITLE
Delete artifacts folder after test-runner completes

### ISSUE THREAD

**Issue by webbertakken** [game-ci/unity-test-runner#58]
In order to not make the branch dirty, test-runner should now create files that are not ignored in git.

There are a few possible approaches:

- Not creating test output at all
- Adding instruction to the readme's to run `rm -rf ${{ steps.testRunner.outputs.artifactsPath }}`
- Putting the artifacts in a folder that is (almost?) always ignored in git in unity project
- Putting the artifacts in a folder outside of /workspace/github (so it's not at the same level as the repo)
- Deleting the artifacts after uploading them from within test-runner itself

Currently when using test runner and builder steps in the same job, builder will pick up the artifacts folder as a change in the branch and mark HEAD as dirty. A temporary workaround is to use the flag `allowDirtyBuild: true` in builder.

**Comment by darrencperry** [comment]
For me the safest option of the above would seem to be:

> Putting the artifacts in a folder outside of /workspace/github (so it's not at the same level as the repo)

They should probably live in /tmp directory since they are temporary files stored until they are uploaded and the repo has no need for them when you're uploading them as artifacts.

Optionally allow overrides in the yml file to specify the directory if you do need the artifacts added to the repo?

**Comment by darrencperry** [comment]
FYI running `rm -rf ${{ steps.testRunner.outputs.artifactsPath }}` after the test runner seems to mess with other concurrent actions i.e. multiple build platforms or Unity versions.

After one action completes the test phase and then runs the rm command, the next action will fail with this kind of error:

```
###########################
#    Edit Mode Results    #
###########################

cat: /github/workspace/artifacts/editmode-results.xml: No such file or directory
cat: /github/workspace/artifacts/editmode-results.xml: No such file or directory

###########################
#    Play Mode Results    #
###########################

cat: /github/workspace/artifacts/playmode-results.xml: No such file or directory
cat: /github/workspace/artifacts/playmode-results.xml: No such file or directory
##[error]The process '/usr/bin/docker' failed with exit code 1
```

**Comment by webbertakken** [comment]
I'm closing this because everyone seems to be doing fine just ignoring the artifacts folder in .gitignore.
