### ISSUE TITLE
Fix file ownership issues for runners

### ISSUE THREAD

**Issue by nussetorten** [game-ci/unity-test-runner#70]
Following in the footsteps of https://github.com/webbertakken/unity-builder/pull/141

Current impl imports assets and generates artifacts as root:root, requiring chown to resolve file ownership errors.  Recommend adopting the elegant solution introduced in unity-builder Action, running container as correct user/group from the get-go.

**Comment by webbertakken** [comment]
Great idea! Accepting PRs.

**Comment by webbertakken** [comment]
This should be fixed by the latest release of the docker images.
